spring.application.name=app
#H2 Database http://localhost:8080/h2-console  JDBC URL: jdbc:h2:mem:test # multiline comment Ctrl + /
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobapp
spring.datasource.username=ani369
spring.datasource.password=admin
spring.jpa.database=POSTGRESQL
#print on console
spring.jpa.show-sql=true
#auto create and drop scema on session creation
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=*
# * or beans or logger: to debug via postman
management.endpoint.health.show-details=always

management.info.env.enabled=true
info.app.name=JobApplication
info.app.description=Job app built by ...
info.app.version=1.0

management.endpoint.shutdown.access=unrestricted
#POST http://localhost:8080/actuator/shutdown  this shuts down via postman
server.shutdown=graceful
#